### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/LocalBroadcastManager;

### ISSUE THREAD

**Issue by androidforme** [TinloneX/MyReplugin#2]
对着文档集成的，啥代码都没有写，一运行就保存，怎么解决？

第一步
 classpath 'com.android.tools.build:gradle:3.1.0'
classpath 'com.qihoo360.replugin:replugin-host-gradle:2.2.4'

第二步
apply plugin: 'replugin-host-gradle'

/**
 * 配置项均为可选配置，默认无需添加
 * 更多可选配置项参见replugin-host-gradle的RepluginConfig类
 * 可更改配置项参见 自动生成RePluginHostConfig.java
 */
repluginHostConfig {
    /**
     * 是否使用 AppCompat 库
     * 不需要个性化配置时，无需添加
     */
    useAppCompat = true
    /**
     * 背景不透明的坑的数量
     * 不需要个性化配置时，无需添加
     */
    countNotTranslucentStandard = 6
    countNotTranslucentSingleTop = 2
    countNotTranslucentSingleTask = 3
    countNotTranslucentSingleInstance = 2
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'com.qihoo360.replugin:replugin-host-lib:2.2.4'

}
第三步
public class MainApplication extends RePluginApplication {
}
第四步
 <application
        android:name=".MainApplication"
机型 模拟器雷电。我运行别人的demo没有奔溃； 区别就是我引入了android.x.

I/art: Late-enabling -Xcheck:jni
D/libnativebridge: call UnloadNativeBridge! state=1
I/art: Debugger is no longer active
 D/RePlugin.ws001: plugin process checker: default, index=0
 D/RePlugin.ws001: PACM: restore table: size=0
 D/RePlugin.ws001: list plugins from persistent process
 D/RePlugin.ws001: get binder = android.os.BinderProxy@2a6ce742
09-21 16:24:16.988 5632-5632/? D/RePlugin.ws001: proxy fetch binder: binder=android.os.BinderProxy@2a6ce742
09-21 16:24:16.988 5632-5632/? D/RePlugin.ws001: host binder = android.os.BinderProxy@2a6ce742
09-21 16:24:16.989 5632-5632/? D/RePlugin.ws001: host binder.i = com.qihoo360.loader2.IPluginHost$Stub$Proxy@1de0c353
09-21 16:24:16.991 5632-5632/? D/PatchClassLoaderUtils: patch: mBase cl=class android.app.ContextImpl; mPackageInfo cl=class android.app.LoadedApk
09-21 16:24:16.991 5632-5632/? D/RePlugin.RePluginClassLoader: copyFieldValue: Copied. f=pathList; actually=DexPathList[[zip file "/data/app/test.pvj.com.test2-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]; orig=DexPathList[[zip file "/data/app/test.pvj.com.test2-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
09-21 16:24:16.992 5632-5632/? D/PatchClassLoaderUtils: patch: patch mClassLoader ok
09-21 16:24:16.993 5632-5632/? D/RePlugin.ws001: plugin provider loader: not found default plugin,  in=test.pvj.com.test2.loader.p.ProviderN1
09-21 16:24:16.993 5632-5632/? W/ws001: p m hlc u d p o test.pvj.com.test2.loader.p.ProviderN1
09-21 16:24:16.994 5632-5632/? D/RePlugin.ws001: initial local cookie=0
09-21 16:24:16.994 5632-5632/? D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
09-21 16:24:16.994 5632-5632/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: test.pvj.com.test2, PID: 5632
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/LocalBroadcastManager;
        at com.qihoo360.loader2.PmBase.registerReceiverAction(PmBase.java:632)
        at com.qihoo360.loader2.PmBase.callAppCreate(PmBase.java:622)
        at com.qihoo360.loader2.PMF.callAppCreate(PMF.java:84)
        at com.qihoo360.replugin.RePlugin$App.onCreate(RePlugin.java:1002)
        at com.qihoo360.replugin.RePluginApplication.onCreate(RePluginApplication.java:74)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
        at android.app.ActivityThread.access$1500(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.LocalBroadcastManager" on path: DexPathList[[zip file "/data/app/test.pvj.com.test2-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.qihoo360.loader2.PmBase.registerReceiverAction(PmBase.java:632) 
        at com.qihoo360.loader2.PmBase.callAppCreate(PmBase.java:622) 
        at com.qihoo360.loader2.PMF.callAppCreate(PMF.java:84) 
        at com.qihoo360.replugin.RePlugin$App.onCreate(RePlugin.java:1002) 
        at com.qihoo360.replugin.RePluginApplication.onCreate(RePluginApplication.java:74) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 
    	Suppressed: java.lang.ClassNotFoundException: android.support.v4.content.LocalBroadcastManager
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 17 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by TinloneX** [comment]
去官方文档看下呢，最近没有关注和使用该技术，可能存在变更。 https://github.com/Qihoo360/RePlugin
